sonar.projectKey=recipebhook
sonar.projectName=RecipeBhook

sonar.sources=accounts,config,recipes,services

sonar.sourceEncoding=UTF-8

sonar.python.version=3.11

sonar.exclusions=**/.venv/**,**/node_modules/**,**/__pycache__/**,**/migrations/**,**/static/**

