# Generated by Django 5.2.17 on 2026-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrecipe',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recipe_audio/'),
        ),
    ]
