# Generated by Django 5.2.17 on 2026-09-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_generatedrecipe_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrecipe',
            name='hindi_audio_file',
            field=models.FileField(blank=True, null=True, upload_to='recipe_audio/hindi/'),
        ),
        migrations.AddField(
            model_name='generatedrecipe',
            name='hindi_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
